### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sendto'

### ISSUE THREAD

**Issue by shbhmsingh72** [jhoward321/PythonP2PBotnet#10]
2018-02-11 18:12:17+0530 [-] Loading server.tac...
2018-02-11 18:12:17+0530 [Server] [WARNING] No known neighbors, so not writing to cache.
2018-02-11 18:12:17+0530 [-] Loaded.
2018-02-11 18:12:17+0530 [-] twistd 17.9.0 (/usr/bin/python3 3.5.2) starting up.
2018-02-11 18:12:17+0530 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-02-11 18:12:17+0530 [-] KademliaProtocol starting on 8468
2018-02-11 18:12:17+0530 [-] Traceback (most recent call last):
2018-02-11 18:12:17+0530 [-]   File "/usr/local/bin/twistd", line 9, in <module>
2018-02-11 18:12:17+0530 [-]     load_entry_point('Twisted==17.9.0', 'console_scripts', 'twistd')()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/scripts/twistd.py", line 29, in run
2018-02-11 18:12:17+0530 [-]     app.run(runApp, ServerOptions)
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 662, in run
2018-02-11 18:12:17+0530 [-]     runApp(config)
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
2018-02-11 18:12:17+0530 [-]     _SomeApplicationRunner(config).run()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 384, in run
2018-02-11 18:12:17+0530 [-]     self.postApplication()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/scripts/_twistd_unix.py", line 248, in postApplication
2018-02-11 18:12:17+0530 [-]     self.startApplication(self.application)
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/scripts/_twistd_unix.py", line 435, in startApplication
2018-02-11 18:12:17+0530 [-]     service.IService(application).privilegedStartService()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/application/service.py", line 279, in privilegedStartService
2018-02-11 18:12:17+0530 [-]     service.privilegedStartService()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/application/internet.py", line 114, in privilegedStartService
2018-02-11 18:12:17+0530 [-]     self._port = self._getPort()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/application/internet.py", line 142, in _getPort
2018-02-11 18:12:17+0530 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/posixbase.py", line 369, in listenUDP
2018-02-11 18:12:17+0530 [-]     p.startListening()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/udp.py", line 179, in startListening
2018-02-11 18:12:17+0530 [-]     self._connectToProtocol()
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/udp.py", line 217, in _connectToProtocol
2018-02-11 18:12:17+0530 [-]     self.protocol.makeConnection(self)
2018-02-11 18:12:17+0530 [-]   File "/usr/local/lib/python3.5/dist-packages/rpcudp/protocol.py", line 121, in func
2018-02-11 18:12:17+0530 [-]     self.transport.sendto(txdata, address)
2018-02-11 18:12:17+0530 [-] AttributeError: 'NoneType' object has no attribute 'sendto'

**Comment by jhoward321** [comment]
You're using the wrong version of python (3.5). This was written for 2.7

**Comment by shbhmsingh72** [comment]
But you have used "import asyncio" which throws exceptions on python (2.7).

**Comment by jhoward321** [comment]
Looks like the kademlia package I used has since been updated to python 3 and now uses asyncio. You'll have to either hunt down the older version of the kademlia package, or update the code for use with python 3. I haven't worked on this project in a few years, and have no reason to update it, but feel free to make changes and submit a pull request if you'd like. [From a quick glance, it looks like this is the last version of kademlia before the switch to asyncio.](https://github.com/bmuller/kademlia/tree/464ae5bd1f78a11958593965db523f8ff9f4e5f2)

**Comment by shbhmsingh72** [comment]
You just need to mention the following requirements in the readme:
Python == 2.7
kademlia == 0.4
rpcudp == 2.1
Everything else works fine. One more thing, Did you ran all the VM's server.tac on 0.0.0.0:8468? I'm currently able to ping every machine from every other machine but I don't know if they are connected after running their scripts because no sign of other machine's ip is visible in one machine's log that is being created in command window.

**Comment by jhoward321** [comment]
Feel free to add a requirements.txt for an easy pip install. Again, this was a school project from a few years ago so I don't really have an incentive to work on it anymore. The code is available for you to do with as you please. 

As for the server.tac, it only needs to be run on 1 of the 3 or more vms. It's acting as a kademlia network for the others to connect to until they've contacted the dht. I haven't run this in a while but I think I ran the server.tac on localhost (127.0.0.1:8468) which i believe is hardcoded into the file. Then when connecting to the network on the commander and clients, you'll need to specify the ip of the vm that they see on their network. Might have to adapt firewall rules to make sure the port is open.
